version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    volumes:
      - kong-database:/var/lib/postgresql/data
    networks:
      - kong-net

  kong:
    image: kong:3.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PORT: 8000
    ports:
      - "8000:8000"  
      - "8443:8443"  
      - "8001:8001"  
    depends_on:
      - kong-database
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    environment:
      - "KONGA_HOST=kong:8001"  
    ports:
      - "1337:1337"  
    depends_on:
      - kong
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  kong-database:
    driver: local
